server:
  shutdown: graceful
  servlet:
    context-path: /showcase
pf-adm:
  enable-slide-menu: true
  render-slide-menu-toggle: true
  skin: skin-purple
  render-brand-text: true
  render-logo: false
  render-full-screen-toggle: false
  render-bread-crumb: true
  support-bootstrap-icons: false
  support-font-awesome: true
  index-page: /web/index.xhtml
  template-path: /WEB-INF/template/template.xhtml
joinfaces:
  faces:
    project-stage: Production
  primefaces:
    theme: admin
